import type { NextPage } from 'next';
import Head from 'next/head';

import Footer from '../components/footer';
import Links from '../components/links';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>About page</h1>

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/about.js</code>
        </p>

        <Links />
      </main>
      <Footer />
    </div>
  );
};

export default Home;
