import type { NextPage } from 'next';
import Head from 'next/head';

import Footer from '../components/Footer';
import Links from '../components/Links';
import styles from '../styles/Home.module.css';
import HeadLine from '../components/HeadLine';

const About: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>About Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <HeadLine page="about" />

        <Links />
      </main>

      <Footer />
    </div>
  );
};

export default About;
