import type { NextPage } from 'next';
import Head from 'next/head';

<<<<<<< HEAD
import Footer from '../components/Footer';
import Links from '../components/Links';
=======
import Footer from '../components/footer';
import Links from '../components/links';
>>>>>>> 5410ea034294b8dd1e4d878b5c28093566dc7551
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Index Page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
<<<<<<< HEAD
        <h1 className={styles.title}>Index Page</h1>
=======
        <h1 className={styles.title}>Index page</h1>
>>>>>>> 5410ea034294b8dd1e4d878b5c28093566dc7551

        <p className={styles.description}>
          Get started by editing{' '}
          <code className={styles.code}>pages/index.js</code>
        </p>

        <Links />
      </main>
<<<<<<< HEAD

=======
>>>>>>> 5410ea034294b8dd1e4d878b5c28093566dc7551
      <Footer />
    </div>
  );
};

export default Home;
